### ISSUE TITLE
create-new-cn-signatures vignette improvements

### ISSUE THREAD

**Issue by cvasq24** [Huntsmanlab/utanos#38]
1) Section II: is copy_numbers_input a copy of segmented_ACNs from section I?
2) Section V: what does basis mean in the graphs? Basis of the NMF?

**Comment by genomaxx** [comment]
This vignette needs general re-factoring into 2 sections:
1. signature exposure calculation
2. signature creation 

Section 2. will be much larger but that's fine.

- [ ] Add sub-section on consensus map use with NMF: `consensusmap()` , see section 4.1 and 4.2 from NMF package
- [ ] Add signature comparisons section: wasserstein distance and else?
- [ ] Add section on relative signatures
- [ ] Expand explanations and interpretations

**Comment by Jacky-Yiu** [comment]
Review:

For the cn-signatures vignette (3rd article from the dropdown)

in II - Extract CN-features:

 - Mention when to use `ExtractCopyNumberFeatures()` or `ExtractRelativeCopyNumberFeatures()`, while both accept similar input, the nature of the input and downstream analysis is different, maybe make a separate article for  `ExtractRelativeCopyNumberFeatures()` ? It would create less confusion for the reader.
 
in III - Determine CN-signature exposures

- missing hyperlink for `ExtractRelativeCopyNumberFeatures()` 
- you mention  signatures 1 and 4 correspond to poor overall survival + breakage-fusion bridge events and whole-genome duplication + PI3K/AKT signalling inactivation respectively. is there a reference or if it mention somewhere else?

in IV.1 - Modelling

- in "Very brief heuristics for what to look for in the values of each metric:", maybe make a table to better organize it, for now it is kinda messy, for example:

**Comment by genomaxx** [comment]
Relative CN sigs needing its own section is a good point and so will be a separate issue.
The rest will be addressed first.
