### ISSUE TITLE
shallowHRD code integration to main package code

### ISSUE THREAD

**Issue by genomaxx** [Huntsmanlab/utanos#41]
The following changes are needed:

1. Remove .jpeg file from /R directory
2. Name find_threshold_1.R more appropriately
3. Create what is known as a dispatcher function out of the code in stitching_functions.R
This function could be named something like `RunShallowHRD()` or the like.
Its purpose is to run the necessary steps in order to generate shallowHRD output (the dataframe).
This function would be called by a user on their sample and it would return the shallowHRD output.
The line: `raw_ratios_file <- data.frame(read.table(file="./test_data/example_1_controlfreec_final_hg19.bam_ratio.txt",header=TRUE))`
needs to be removed for example in favour for a user passed in path or object (please allow for either).
The line: `write.table(final_lga_res, "./test_outputs/controlfreec_number_of_lgas.txt", sep="\t", row.names = FALSE)`
should be modified in favour of letting the user define the output path.
See the CalculateACNs function for design example.
`
if (acn_save_path != FALSE) {
    saveRDS(output[[1]], file = acn_save_path)
  }
  return(output)
}`

A lot, if not all, of the (excellent) explanatory text currently in this file will be moved to a vignette.
This text should be replaced with a more streamlined description of what steps are executed by the function in the standard ROxygen format.
4. Remove testing files from the /R section (I'll be asking Branden to begin expanding the test suite so perhaps co-ordinate with him for what to do with any existing testing-specific files) 
I believe this includes files like compare_files.R?
5. Move all R files into the same directory as the rest of the utanos files. No more shallow_hrd folder. 
6. None of your files should include source() calls to utanos code. All utanos functions are discoverable in the local namespace as long as they are in /R
7. Remove all library() calls from the beginning of files and call functions specifically prefixing the appropriate package. For example to use a genomic ranges method you would make the function call like so:
`GenomicRanges::makeGRangesFromDataFrame()`
Note this is not necessary for utanos functions.
Read the page: https://r-pkgs.org/code.html if a refresher is needed on these details.

**Comment by brandenjlynch** [comment]
Currently we reference `shrd_hg19_segements.R` to determine blacklisted regions; we should refactor this to use the bundled blacklists. Also, we should make all functions robust to hg38, mm10.

**Comment by genomaxx** [comment]
Two questions:
1.
I made reference to some good explanatory text in the function documentation that should maybe be moved to or copied to the vignette on running HRD calling.
Would you agree @brandenjlynch ?
2.
Will this issue then be fully addressed by PR#70?

**Comment by brandenjlynch** [comment]
Yep, much of explanatory text will be moved to / re-visited in the vignette, so this issue will be covered by the PR.

**Comment by genomaxx** [comment]
So close issue?

**Comment by brandenjlynch** [comment]
Resolved by: [https://github.com/Huntsmanlab/utanos/pull/70](PR 70)
