### ISSUE TITLE
Relative copy-number profile quality evaluation - automated MVP

### ISSUE THREAD

**Issue by genomaxx** [Huntsmanlab/utanos#44]
Push a version of the quality evaluation code for utanos that automates the quality call.
(as discussed more thoroughly over zoom)
This should include a basic figure/plot to demonstrate the effect.
@ntmv - ping if further clarification is required.

**Comment by genomaxx** [comment]
Is this function CollapsedSegs a duplicate of CopyNumberSegments?
Double check.

**Comment by brandenjlynch** [comment]
Plot: scatterplot with segment count on x-axis, and variance on y-axis.

**Comment by genomaxx** [comment]
Branden MVP version pushed in time for ISMB2024 abstract deadline.
Definitely still needs work.
We are thinking other features besides per-segment variance/segment count. 
The question is what other features... 🤔 good vs. useable profiles are clear enough to determine by eye.
