### ISSUE TITLE
toy data missing for cn-summary-workflow.md vignette

### ISSUE THREAD

**Issue by mdeea** [Huntsmanlab/utanos#58]
Hi there,

I am trying to work through your vignettes.
The link to the toy dataset appears to be broken. https://github.com/Huntsmanlab/utanosmodellingdata/tree/main/sample_copynumber_data
Is this repo public?

Merridee

**Comment by genomaxx** [comment]
Hi Merridee - no its still private - will be making public very soon (next two weeks).
Also note, this package in under heavy active development right now and we haven't quite gotten to updating the vignettes quite yet! They are going to change quite a bit. 
If you were to wait a few weeks they will probably be updated

**Comment by genomaxx** [comment]
The utanosmodellingdata repository Has now been made public.
See it here: https://github.com/Huntsmanlab/utanosmodellingdata 
PR #64 provides an updated CN-Diversity/Summary workflow using utanos.
