### ISSUE TITLE
Remove extraneous/unused code

### ISSUE THREAD

**Issue by brandenjlynch** [Huntsmanlab/utanos#62]
There are a few functions which are overly-specific to one dataset and hence lack a general use case. These, and other obsolete functions should potentially be removed:

- [x] SampleGrouping() in samplequality.R
- [x] PlotCellularityAndMaxVaf() in plotting.R
- [x] PlotBABAM() in plotting.R
- [x] PlotMetadataHeatmaps() in plotting.R 
- [x] AddViralPresence() in plotting.R

These may be removed, pending updates that replace them/testing:

- [ ] SummaryCNPlot in plotting.R
- [x] RelativeCNSegmentsPlot in plotting.R

Files:
- [x] When ready, remove the nearly outdated quickstart vignette as it has mostly been made redundant.

**Comment by genomaxx** [comment]
First 5 of those redundant functions we've found removed in my current branch.
Will be included in next PR.

**Comment by genomaxx** [comment]
PR #80 addresses a good half of this issue.

**Comment by genomaxx** [comment]
The SummaryCNPlot function in plotting.R will need to be re-written. 
This is an appropriate standalone issue and so will be addressed there.
No tasks left to address so closing ticket.
